//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "environment_configurations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub environment_id: Uuid,
    pub name: String,
    pub r#type: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::environment::Entity",
        from = "Column::EnvironmentId",
        to = "super::environment::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Environment3,
    #[sea_orm(
        belongs_to = "super::environment::Entity",
        from = "Column::EnvironmentId",
        to = "super::environment::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Environment2,
    #[sea_orm(
        belongs_to = "super::environment::Entity",
        from = "Column::EnvironmentId",
        to = "super::environment::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Environment1,
}

impl ActiveModelBehavior for ActiveModel {}
